# -*- coding: utf-8 -*-
"""python assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Qks-mDv9Z99prT_YkfD592v9s4ed5WX
"""

#arithematic operations
distance = float(1000.0)
time = float(143.5)
speed = float((5/18)*100000/143.5)
print(speed)

#average time per mile

distance = float(1000*1.61)
time = float(143.5)
speed = float(distance/time)
time_taken = speed*distance
print("time take is", time_taken, "minutes")

cover_price = float (577.95)

cost = float((577.95+150) + (577.95+50)*59)
discount = float(cost*0.4)
final_cost = float(cost-discount)
print("final cost is", final_cost)

#centigrade to faranhite
centigrade = float(input("please enter temperature in centigrade \t"))
faranhite = float(centigrade*1.8+32)
print(faranhite)

my_float = float(2.4)
print(my_float)

my_neg = -5
print(my_neg)

complex_num = complex(4,5)
print(complex_num)

c1 = 5+4j
print(c1)
print(type(c1))

#add complex numbers
c1 = complex(5,6)
c2 = complex(5,7)
c3 = complex(c1+c2)
print(c3)

c6 = complex(c1/c2)
print(c6)

c4 = complex(c1-c2)
print(c4)

c5 = complex(c1*c2)
print(c5)

break = 15

result = "hello"
print(result[0])

#greetings
name = input("please enter your name")
print("hearty welcome \t", name)

#string operations
quote = "When the seed looses completely in the earth, Only then can it become a Tree"
count =0
new_quote = ""
for i in range(0,len(quote)):
  count = count + 1
print(count)

print(len(quote))

print(quote.upper())

for i in quote:
  if(i.islower()) == True:
    new_quote+=(i.upper())
  else:
    new_quote+=i

print(new_quote)

c = a+b
a = 10
b = 12

"""intialisation of the variable is happening after the opertion, it throws an error"""

c = 4+45j
abso = abs(c)
print(abso)

r = 4.5
print(round(r))

quote = "hello world."
print(quote.replace(".", "!"))

